### PR TITLE
Log suppressed exceptions in MillisecondPrecisionSyslogAppender

### PR DESCRIPTION
**Pull request by totalorder**
This adds support for logging suppressed exceptions. Without this change they are silently ignored contrary to a regular throwable.printStackTrace() which does print them.
Inspiration has been taken from the upstream implementation in another appender: https://github.com/qos-ch/logback/blob/master/logback-classic/src/main/java/ch/qos/logback/classic/pattern/RootCauseFirstThrowableProxyConverter.java#L33

### CODE REVIEW

**Comment by totalorder** [comment]
Is there a reasonably easy way to write tests for this class? I don't even know where to start.
In the mean time we are testing this by shadowing it in our service. Testing in production :cowboy_hat_face: https://ghe.spotify.net/search-platform/search-api/pull/1116

**Comment by totalorder** [comment]
@danielnorberg @pettermahlen Please take a look

**Comment by totalorder** [comment]
@pettermahlen We have been running this in production for ~10 days and it seems to work well. Would you mind merging it?

**Comment by totalorder** [comment]
@pettermahlen Thanks! I saw the last release was ~1 year ago. Is there still someone around who knows how to make a new release of this package? :)

**Comment by pettermahlen** [comment]
@totalorder I will dare it, any time now :) Not sure that the current laptop is set up for it, but we'll see. Not sure I'll get to it today, a lot of meetings.

**Comment by pettermahlen** [comment]
2.2.7 is now out and available via Maven Central.

**Comment by totalorder** [comment]
Awesome! You are a brave soul

**Pull request merged**
